ALTER TABLE TRANSAKSI DROP CONSTRAINT ID_MEMBER;
ALTER TABLE PEGAWAI DROP CONSTRAINT ID_JABATAN;
ALTER TABLE SHIFT_SPESIALIS DROP CONSTRAINT ID_PEGAWAI;
ALTER TABLE SHIFT_SPESIALIS DROP CONSTRAINT ID_PERAWATAN;
ALTER TABLE SHIFT_SPESIALIS DROP CONSTRAINT ID_RUANG;
ALTER TABLE DTRANS_RUANG DROP CONSTRAINT ID_RUANG_TRANS;
ALTER TABLE DTRANS_RUANG DROP CONSTRAINT ID_TRANS_RUANG;
ALTER TABLE DTRANS_PEMBAYARAN DROP CONSTRAINT ID_PEMBAYARAN;
ALTER TABLE DTRANS_PEMBAYARAN DROP CONSTRAINT ID_TRANS;
ALTER TABLE DTRANS_SUPPLY DROP CONSTRAINT ID_SUPPLY;
ALTER TABLE DTRANS_SUPPLY DROP CONSTRAINT ID_TRANS_SUPPLY;
ALTER TABLE DONOR DROP CONSTRAINT ID_MEMBER_DONOR;
ALTER TABLE DONOR DROP CONSTRAINT ID_SUPPLY_DONOR;
ALTER TABLE DTRANS_PERAWATAN_INAP DROP CONSTRAINT ID_TRANS_CHECKUP;
ALTER TABLE DTRANS_PERAWATAN_INAP DROP CONSTRAINT ID_PERAWATAN_CHECKUP;
ALTER TABLE DTRANS_PERAWATAN_INAP DROP CONSTRAINT ID_PEGAWAI_CHECKUP;
ALTER TABLE DTRANS_JALAN DROP CONSTRAINT ID_TRANS_JALAN;
ALTER TABLE DTRANS_JALAN DROP CONSTRAINT ID_PERAWATAN_JALAN;
ALTER TABLE DTRANS_JALAN DROP CONSTRAINT ID_PEGAWAI_JALAN;
ALTER TABLE ISI_STOK DROP CONSTRAINT ID_PRODUSEN;
ALTER TABLE DTRANS_STOK DROP CONSTRAINT ID_TRANS_STOK;
ALTER TABLE DTRANS_STOK DROP CONSTRAINT ID_SUPPLY_STOK;

DROP TABLE MEMBER;
DROP TABLE SUPPLY;
DROP TABLE TRANSAKSI;
DROP TABLE PEGAWAI;
DROP TABLE JABATAN;
DROP TABLE PERAWATAN;
DROP TABLE PEMBAYARAN;
DROP TABLE table_1;
DROP TABLE PRODUSEN;
DROP TABLE RUANG;
DROP TABLE SHIFT_SPESIALIS;
DROP TABLE DTRANS_RUANG;
DROP TABLE DTRANS_PEMBAYARAN;
DROP TABLE DTRANS_SUPPLY;
DROP TABLE DONOR;
DROP TABLE table_2;
DROP TABLE SURAT_TUGAS;
DROP TABLE DTRANS_PERAWATAN_INAP;
DROP TABLE table_3;
DROP TABLE DTRANS_JALAN;
DROP TABLE ISI_STOK;
DROP TABLE DTRANS_STOK;
DROP TABLE JENIS_PERAWATAN;

CREATE TABLE MEMBER (
ID_MEMBER VARCHAR2(5) NOT NULL,
NAMA_MEMBER VARCHAR2(50) NOT NULL,
TGLLAHIR_MEMBER DATE NOT NULL,
ALAMAT_MEMBER VARCHAR2(50) NOT NULL,
TELP_MEMBER VARCHAR2(12) NOT NULL,
GOL_DARAH VARCHAR2(1) NOT NULL,
PEKERJAAN_MEMBER VARCHAR2(30) NOT NULL,
AGAMA VARCHAR2(20) NOT NULL,
JK_MEMBER VARCHAR2(1) NOT NULL,
NIK VARCHAR2(16) NOT NULL,
PRIMARY KEY (ID_MEMBER) 
);
CREATE TABLE SUPPLY (
ID_SUPPLY VARCHAR2(5) NOT NULL,
NAMA_SUPPLY VARCHAR2(30) NOT NULL,
DESKRIPSI_SUPPLY VARCHAR2(100) NOT NULL,
HARGA_SUPPLY NUMBER NOT NULL,
PRIMARY KEY (ID_SUPPLY) 
);
CREATE TABLE TRANSAKSI (
ID_TRANS VARCHAR2(12) NOT NULL,
TGL_MASUK DATE NOT NULL,
TGL_KELUAR DATE NULL,
KONDISI_KELUAR VARCHAR2(100) NULL,
TOTAL_TRANSAKSI NUMBER NOT NULL,
ID_MEMBER VARCHAR2(5) NOT NULL,
STATUS_PELUNASAN VARCHAR2(1) NOT NULL,
DIAGNOSA_MASUK VARCHAR2(255) NULL,
PRIMARY KEY (ID_TRANS) 
);
CREATE TABLE PEGAWAI (
ID_PEGAWAI VARCHAR2(5) NOT NULL,
NAMA_PEGAWAI VARCHAR2(50) NOT NULL,
TELP_PEGAWAI VARCHAR2(12) NOT NULL,
TGLLAHIR_PEGAWAI DATE NOT NULL,
ALAMAT_PEGAWAI VARCHAR2(50) NOT NULL,
NIK VARCHAR2(16) NOT NULL,
ID_JABATAN VARCHAR2(5) NOT NULL,
PRIMARY KEY (ID_PEGAWAI) 
);
CREATE TABLE JABATAN (
ID_JABATAN VARCHAR2(3) NOT NULL,
NAMA_JABATAN VARCHAR2(30) NOT NULL,
GAJI_JABATAN NUMBER NOT NULL,
PRIMARY KEY (ID_JABATAN) 
);
CREATE TABLE PERAWATAN (
ID_PERAWATAN VARCHAR2(5) NOT NULL,
NAMA_PERAWATAN VARCHAR2(30) NOT NULL,
DESKRIPSI_PERAWATAN VARCHAR2(100) NOT NULL,
HARGA_PERAWATAN NUMBER NOT NULL,
PRIMARY KEY (ID_PERAWATAN) 
);
CREATE TABLE PEMBAYARAN (
ID_PEMBAYARAN VARCHAR2(3) NOT NULL,
NAMA_PEMBAYARAN VARCHAR2(30) NOT NULL,
PRIMARY KEY (ID_PEMBAYARAN) 
);
CREATE TABLE PRODUSEN (
ID_PRODUSEN VARCHAR2(5) NOT NULL,
NAMA_PRODUSEN VARCHAR2(30) NOT NULL,
PRIMARY KEY (ID_PRODUSEN) 
);
CREATE TABLE RUANG (
ID_RUANG VARCHAR2(5) NOT NULL,
NOMOR_RUANG VARCHAR2(3) NOT NULL,
JENIS_RUANG VARCHAR2(30) NOT NULL,
HARGA_RUANG NUMBER NULL,
PRIMARY KEY (ID_RUANG) 
);
CREATE TABLE SHIFT_SPESIALIS (
ID_PEGAWAI VARCHAR2(5) NOT NULL,
ID_PERAWATAN VARCHAR2(5) NOT NULL,
WAKTU_MULAI DATE NOT NULL,
WAKTU_SELESAI DATE NOT NULL,
ID_RUANG VARCHAR2(5) NOT NULL,
ID_SHIFT VARCHAR2(8) NOT NULL,
HARGA_SHIFT NUMBER NOT NULL,
PRIMARY KEY (ID_SHIFT) 
);
CREATE TABLE DTRANS_RUANG (
ID_RUANG VARCHAR2(5) NOT NULL,
ID_TRANS VARCHAR2(12) NOT NULL,
TOTAL_HARI NUMBER NOT NULL,
SUBTOTAL NUMBER NOT NULL,
PRIMARY KEY (ID_RUANG, ID_TRANS) 
);
CREATE TABLE DTRANS_PEMBAYARAN (
ID_PEMBAYARAN VARCHAR2(3) NOT NULL,
ID_TRANS VARCHAR2(12) NOT NULL,
JUMLAH_PEMBAYARAN NUMBER NOT NULL,
PRIMARY KEY (ID_TRANS, ID_PEMBAYARAN) 
);
CREATE TABLE DTRANS_SUPPLY (
ID_SUPPLY VARCHAR2(5) NOT NULL,
ID_TRANS VARCHAR2(12) NOT NULL,
JUMLAH NUMBER NOT NULL,
SUBTOTAL NUMBER NOT NULL,
PRIMARY KEY (ID_SUPPLY) 
);
CREATE TABLE DONOR (
ID_DONOR VARCHAR2(12) NOT NULL,
ID_MEMBER VARCHAR2(5) NOT NULL,
ID_SUPPLY VARCHAR2(5) NOT NULL,
TENSI_MEMBER VARCHAR2(10) NOT NULL,
SUHU_MEMBER NUMBER NOT NULL,
REAKSI_DONOR VARCHAR2(255) NOT NULL,
KETERANGAN_DONOR VARCHAR2(255) NULL,
TGL_DONOR DATE NOT NULL,
PRIMARY KEY (ID_DONOR) 
);
CREATE TABLE DTRANS_PERAWATAN_INAP (
ID_TRANS VARCHAR2(12) NOT NULL,
ID_PERAWATAN VARCHAR2(5) NOT NULL,
ID_PEGAWAI VARCHAR2(5) NOT NULL,
CTR_CHECKUP NUMBER NOT NULL,
KETERANGAN_CHECKUP VARCHAR2(255) NOT NULL,
PRIMARY KEY (ID_TRANS, CTR_CHECKUP) 
);
CREATE TABLE DTRANS_JALAN (
ID_TRANS VARCHAR2(12) NOT NULL,
ID_PERAWATAN VARCHAR2(5) NOT NULL,
CTR_JALAN NUMBER NOT NULL,
KONDISI_JALAN VARCHAR2(255) NULL,
ID_PEGAWAI VARCHAR2(5) NOT NULL,
PRIMARY KEY (ID_TRANS, CTR_JALAN) 
);
CREATE TABLE ISI_STOK (
ID_TRANS_STOK VARCHAR2(12) NOT NULL,
ID_PRODUSEN VARCHAR2(255) NOT NULL,
TGL_TRANS_STOK DATE NOT NULL,
TANDA_TERIMA VARCHAR2(50) NOT NULL,
PRIMARY KEY (ID_TRANS_STOK) 
);
CREATE TABLE DTRANS_STOK (
ID_TRANS_STOK VARCHAR2(12) NOT NULL,
ID_SUPPLY VARCHAR2(5) NOT NULL,
TOTAL_STOK NUMBER NOT NULL,
JML_BELI NUMBER NOT NULL,
PRIMARY KEY (ID_TRANS_STOK, ID_SUPPLY) 
);

ALTER TABLE TRANSAKSI ADD CONSTRAINT ID_MEMBER FOREIGN KEY (ID_MEMBER) REFERENCES MEMBER (ID_MEMBER);
ALTER TABLE PEGAWAI ADD CONSTRAINT ID_JABATAN FOREIGN KEY (ID_JABATAN) REFERENCES JABATAN (ID_JABATAN);
ALTER TABLE SHIFT_SPESIALIS ADD CONSTRAINT ID_PEGAWAI FOREIGN KEY (ID_PEGAWAI) REFERENCES PEGAWAI (ID_PEGAWAI);
ALTER TABLE SHIFT_SPESIALIS ADD CONSTRAINT ID_PERAWATAN FOREIGN KEY (ID_PERAWATAN) REFERENCES PERAWATAN (ID_PERAWATAN);
ALTER TABLE SHIFT_SPESIALIS ADD CONSTRAINT ID_RUANG FOREIGN KEY (ID_RUANG) REFERENCES RUANG (ID_RUANG);
ALTER TABLE DTRANS_RUANG ADD CONSTRAINT ID_RUANG_TRANS FOREIGN KEY (ID_RUANG) REFERENCES RUANG (ID_RUANG);
ALTER TABLE DTRANS_RUANG ADD CONSTRAINT ID_TRANS_RUANG FOREIGN KEY (ID_TRANS) REFERENCES TRANSAKSI (ID_TRANS);
ALTER TABLE DTRANS_PEMBAYARAN ADD CONSTRAINT ID_PEMBAYARAN FOREIGN KEY (ID_PEMBAYARAN) REFERENCES PEMBAYARAN (ID_PEMBAYARAN);
ALTER TABLE DTRANS_PEMBAYARAN ADD CONSTRAINT ID_TRANS FOREIGN KEY (ID_TRANS) REFERENCES TRANSAKSI (ID_TRANS);
ALTER TABLE DTRANS_SUPPLY ADD CONSTRAINT ID_SUPPLY FOREIGN KEY (ID_SUPPLY) REFERENCES SUPPLY (ID_SUPPLY);
ALTER TABLE DTRANS_SUPPLY ADD CONSTRAINT ID_TRANS_SUPPLY FOREIGN KEY (ID_TRANS) REFERENCES TRANSAKSI (ID_TRANS);
ALTER TABLE DONOR ADD CONSTRAINT ID_MEMBER_DONOR FOREIGN KEY (ID_MEMBER) REFERENCES MEMBER (ID_MEMBER);
ALTER TABLE DONOR ADD CONSTRAINT ID_SUPPLY_DONOR FOREIGN KEY (ID_SUPPLY) REFERENCES SUPPLY (ID_SUPPLY);
ALTER TABLE DTRANS_PERAWATAN_INAP ADD CONSTRAINT ID_TRANS_CHECKUP FOREIGN KEY (ID_TRANS) REFERENCES TRANSAKSI (ID_TRANS);
ALTER TABLE DTRANS_PERAWATAN_INAP ADD CONSTRAINT ID_PERAWATAN_CHECKUP FOREIGN KEY (ID_PERAWATAN) REFERENCES PERAWATAN (ID_PERAWATAN);
ALTER TABLE DTRANS_PERAWATAN_INAP ADD CONSTRAINT ID_PEGAWAI_CHECKUP FOREIGN KEY (ID_PEGAWAI) REFERENCES PEGAWAI (ID_PEGAWAI);
ALTER TABLE DTRANS_JALAN ADD CONSTRAINT ID_TRANS_JALAN FOREIGN KEY (ID_TRANS) REFERENCES TRANSAKSI (ID_TRANS);
ALTER TABLE DTRANS_JALAN ADD CONSTRAINT ID_PERAWATAN_JALAN FOREIGN KEY (ID_PERAWATAN) REFERENCES PERAWATAN (ID_PERAWATAN);
ALTER TABLE DTRANS_JALAN ADD CONSTRAINT ID_PEGAWAI_JALAN FOREIGN KEY (ID_PEGAWAI) REFERENCES PEGAWAI (ID_PEGAWAI);
ALTER TABLE ISI_STOK ADD CONSTRAINT ID_PRODUSEN FOREIGN KEY (ID_PRODUSEN) REFERENCES PRODUSEN (ID_PRODUSEN);
ALTER TABLE DTRANS_STOK ADD CONSTRAINT ID_TRANS_STOK FOREIGN KEY (ID_TRANS_STOK) REFERENCES ISI_STOK (ID_TRANS_STOK);
ALTER TABLE DTRANS_STOK ADD CONSTRAINT ID_SUPPLY_STOK FOREIGN KEY (ID_SUPPLY) REFERENCES SUPPLY (ID_SUPPLY);

--FUNCTION/PROCEDURE/TRIGGER--
create or replace function AUTO_GEN_ID_MEMBER(a varchar2)
return varchar2
is
    hasil varchar2(3);
begin
    select LPAD(count(ID_MEMBER),3,'0') into hasil from MEMBER where ID_MEMBER like '%'||a||'%';
    return hasil;
end;
/
show err;
